### ISSUE TITLE
Persistente Speicherung in Redux 

### ISSUE THREAD

**Issue by Amythethird** [Amythethird/Batta#108]

**Comment by mweiershaeuser** [comment]
@Amythethird Ist das hier eigentlich noch relevant? Soweit ich mich erinnere ging es darum, dass die abgefragten Shops persistiert werden, damit sie bei Aufruf der Shop-Detail-Seite weiterhin zur Verfügung stehen. Das haben wir jetzt ja anders gelöst (separate Abfrage, da GraphQL dann sparsamere Requests für die Shop-Suche ermöglicht). Die Task ist damit hinfällig oder?
