### ISSUE TITLE
Fragen Katalog

### ISSUE THREAD

**Issue by JanKoll** [Amythethird/Batta#155]

**Comment by acvm007** [comment]
- Wann soll gespendet werden? Nach jeder Zahlung oder einmal im Monat?
- Was passiert wenn ein Kunde seine Zahlung zurückzieht (zB via PayPal)?
- Wie lange dürfen wir das Geld halten? Muss das gemeldet werden? 
- Dürfen/Sollen wir etwas von dem Geld anlegen das wir halten?
- Wann verfällt ein Gutschein?
   -  [Was ist bei Gutscheinen zu beachten?](https://www.ihk-muenchen.de/de/Service/Recht-und-Steuern/Vertragsrecht/gutscheine/)
- Wie funktioniert die Weitergabe des Geldes an Shopbetreiber:innen genau?
- Was passiert wenn ein Shop pleite geht?
   - Insolvenzverfahren recherchieren
- Was passiert wenn wir pleite gehen?
- Was passiert mit den Gutscheinen wenn ein Shop aus der Genossenschaft austritt/den Vertrag kündigt?
- Wie können Gutscheine im Geschäft eingelöst werden?

**Comment by Amythethird** [comment]
Aufteilung der Fragen in Kaufmännisch-Rechtlich, Gesellschaftlich-Rechtlich, Bankrechtlich (BaFin)

- Frage 1 -> Sinnvoll wäre es einmal im Monat (Transaktionsgebühren) 

- Frage 2 -> Außenvor lassen da selten 

- Frage 3 & 4 -> Bankrechtliche Frage

- Frage 5 -> Kaufmännische Frage -> Klären

- Frage 6 -> Monatliche auszahlung bei einlösen eines Gutscheins
- Frage 7 -> Gesellschaftsrechtliche Frage 
- Frage 8 -> Gesellschaftrechtliche Frage
- Frage 9 -> Gesellschaftrechtliche Frage
- Frage 10 -> Kaufmännisch / Backend

**Comment by mweiershaeuser** [comment]
# Übergreifende Fragen
- Wird das Geld bis zum Einlösen eines Gutscheins bei uns oder bei den Shopbetreibenden liegen?
- Was passiert mit den Geldern, wenn ein Shop den Vertrag kündigt? 
  - Muss der Betrag sofort ausgezahlt werden? Verfällt das Geld für Händler:innen?
- Was passiert mit Anspruch auf Provisonen, wenn Shopbetreibende das Geld einziehen? 
  - Wie muss die Rechnung gestellt werden?
  - Was passiert wenn sich Shopbetreibende weigern, die Provisionen zu zahlen?
- Was passiert wenn ein Shop Insolvenz anmeldet? 
  - Werden die Verträge mit uns automatisch gekündigt? Müssen die Gelder sofort ausgezahlt werden?
- Was passiert, wenn unsere Plattform down ist? Haben wir Garantiepflichten bezüglich der Verfügbarkeit?

# Kaufmännische Fragen (Fragen an Rechtsberatung/Kaufmännische:r Expert:in)
- Wann laufen Gutscheine ab?
- Wie wird unsere Dienstleistung am besten verrechnet (jeweils auf Seite der Kund:innen sowie der Shopbetreibenden)
  - Wie wird unsere "Provision" in Rechnung gestellt? Monatliche Rechnung? Direkter Abzug? ...?
- Was passiert mit Restbeträgen? Bestehen Ansprüche der Kund:innen?

# Gesellschaftsrechtliche Fragen (Fragen an Rechtsberatung)
- Wie müssen Veträge bei einer Genossenschaft aussehen?
- Was passiert, wenn wir als Genossenschaft pleite gehen? 
  - Was passiert mit offenen Gutscheinen?
  
# Finanzrechtliche Fragen (Fragen an Bank)
- Wann soll gespendet werden? Nach jeder Zahlung oder nach einem Monat?
- Welches Bankkonto gibt es für solche Transaktionen?
  - Wäre ein Treuhandkonto sinnvoll?
    - Wie hoch sind die Kosten? Wie hoch sind Transaktionsgebühren, wenn das Geld überwiesen wird?
    - Gibt es andere/bessere Alternativen?
- Brauchen wir eine BaFin-Lizenz?
- Welche Rahmenbedingungen gibt es für Transaktionen, die Spenden sind (z. B. Gebührenerlass)?
- Gibt es Spendenkonten?

# Steuerrechtliche Fragen (Fragen an Steuerberatung)
- Wie werden Gutscheine bei der Umsatzsteuer (Vorsteuer) behandelt (sowohl beim Gutscheinkauf, als auch beim Einlösen und Auszahlen des Gutscheinwerts)?

**Comment by mweiershaeuser** [comment]
https://github.com/Amythethird/Batta/wiki/Fragenkatalog
