### ISSUE TITLE
ADR´s anpassen

### ISSUE THREAD

**Issue by Amythethird** [Amythethird/Batta#65]

**Comment by Amythethird** [comment]
Es muss noch angepasst werden: 
30 -51

**Comment by mweiershaeuser** [comment]
@Darkkap @acvm007 @JanKoll @Amythethird
Aktualisierung oder Ablösung benötigt:
- 30: Die Datenbank im eigentlichen Sinne wurde durch Strapi abgelöst.
- 31: Hier ist Strapi eingetragen. Aber @JanKoll meinst du mit LightQL SQLite?
- 40: Wir haben jetzt ja gar keine Microservices mehr durch Strapi. 😅
- 41: Schnittstellen Design muss angepasst werden auf GraphQL-Entscheidung mit REST-Option für das eventuelle Backend?
- 42: Obsolet weil keine Microservices?
- 50: Testing Konzept ist noch ein ToDo, vielleicht kann der aber auch erstmal so bleiben?
- 51: Entscheidung für Jest (zumindest im Frontend)

& ggf. neue benötigte ADRs
